import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# ==========================================
# 1. CONFIGURATION & MAPPINGS
# ==========================================
# Define Class Names (Alphabetical Order 0-8 mapping to your Short Labels)
class_labels_alpha = [
    'LF8', 'LF6', 'LF3',
    'LF5', 'LF4', 
    'LF1', 'LF2', 
    'LF9', 'LF7'
]

# ==========================================
# 2. COMPARATIVE PLOTTING FUNCTION
# ==========================================
def plot_comparative_class_uncertainty(models_data, champion_model, output_filename):
    """
    Generates a comparative grouped bar chart for epistemic uncertainty across facies.
    
    Args:
        models_data (list of dicts): Format: [{'Model': 'Name', 'Uncertainty': array, 'Facies_Index': array}]
        champion_model (str): The model name used to sort the bars (highest to lowest).
        output_filename (str): Name of the file to save the plot.
    """
    print(f"\n--- Generating Comparative Uncertainty Plot ---")
    
    # 1. Build and Combine DataFrames dynamically
    df_list = []
    for data in models_data:
        df = pd.DataFrame({
            'Uncertainty': data['Uncertainty'],
            'Facies_Index': data['Facies_Index'],
            'Model': data['Model']
        })
        # Map index to short label
        df['Facies'] = df['Facies_Index'].map(lambda x: class_labels_alpha[int(x)])
        df_list.append(df)
        
    df_combined = pd.concat(df_list, axis=0)

    # 2. Calculate Mean Uncertainty per Facies per Model
    df_means = df_combined.groupby(['Facies', 'Model'])['Uncertainty'].mean().reset_index()

    # 3. Determine Sorting Order (Based on the Champion Model)
    champion_data = df_means[df_means['Model'] == champion_model]
    if not champion_data.empty:
        sort_order = champion_data.sort_values('Uncertainty', ascending=False)['Facies'].tolist()
    else:
        # Fallback if champion model name is typed incorrectly
        fallback_model = models_data[0]['Model']
        sort_order = df_means[df_means['Model'] == fallback_model].sort_values('Uncertainty', ascending=False)['Facies'].tolist()

    # ==========================================
    # 3. RENDER PLOT
    # ==========================================
    plt.figure(figsize=(12, 8))
    sns.set_style("ticks")

    # Dynamic palette generation (Assigns colors if you have more than 2 models)
    default_colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
    model_names = [d['Model'] for d in models_data]
    palette = {name: default_colors[i % len(default_colors)] for i, name in enumerate(model_names)}

    # Create Grouped Bar Plot
    ax = sns.barplot(
        data=df_means,
        x='Uncertainty',
        y='Facies',
        hue='Model',
        order=sort_order,  
        palette=palette,
        edgecolor='black',
        linewidth=1.2
    )

    # --- Add Value Labels ---
    for container in ax.containers:
        ax.bar_label(container, fmt='%.4f', padding=5, fontsize=18)

    # Formatting
    plt.xlabel('Average Epistemic Uncertainty (Nats)', fontsize=25)
    plt.ylabel('Lithofacies Class', fontsize=25)
    plt.legend(title='Model Architecture', title_fontsize=20, fontsize=20, loc='lower right')
    
    # Scale X-axis dynamically to fit labels
    plt.xlim(0, df_means['Uncertainty'].max() * 1.25) 
    plt.xticks(fontsize=20)
    plt.yticks(fontsize=20)
    plt.grid(False)

    # Save Output
    os.makedirs('Final_Figures_Paper', exist_ok=True)
    save_path = os.path.join('Final_Figures_Paper', output_filename)
    plt.savefig(save_path, dpi=600, format='tiff', bbox_inches='tight')
    
    print(f"✅ Comparative plot successfully saved to {save_path}")
    plt.show()

# ==========================================
# 4. EXECUTION BLOCK
# ==========================================
if __name__ == "__main__":
    
    # --- INJECT YOUR EXTRACTED UNCERTAINTY DATA HERE ---
    # These arrays (uc_blind2_GRU, y_actual_blind2_GRU, etc.) would be 
    # generated by your uncertainty_mcdo.py script.
    
    # EXAMPLE USAGE (Replace with your actual 1D numpy arrays):
    # uc_blind2_GRU = np.random.rand(1000) 
    # y_actual_blind2_GRU = np.random.randint(0, 9, 1000)
    # uc_blind2_LSTM = np.random.rand(1000) * 0.8  # Just making LSTM slightly lower for dummy data
    # y_actual_blind2_LSTM = y_actual_blind2_GRU 
    
    # Package the models into a dynamic list
    # models_to_compare = [
    #     {
    #         'Model': 'Bi-GRU-LTN', 
    #         'Uncertainty': uc_blind2_GRU, 
    #         'Facies_Index': y_actual_blind2_GRU
    #     },
    #     {
    #         'Model': 'Bi-LSTM-LTN', 
    #         'Uncertainty': uc_blind2_LSTM, 
    #         'Facies_Index': y_actual_blind2_LSTM
    #     }
    # ]
    
    # Run the function
    # plot_comparative_class_uncertainty(
    #     models_data=models_to_compare, 
    #     champion_model='Bi-GRU-LTN',      # Sorts the chart based on GRU's highest uncertainties
    #     output_filename='UC_Classwise_W5.tiff'
    # )
    pass